### ISSUE TITLE
marche pas

### ISSUE THREAD

**Issue by beoschma** [JeromeCisco/isThisIpUsed#1]
File "isThisIpUsed-master/isAddressUsed.py", line 45, in <module>
    config.read(results.config_file)
  File "C:\Python27\lib\ConfigParser.py", line 300, in read
    for filename in filenames:
TypeError: 'NoneType' object is not iterable

**Comment by JeromeCisco** [comment]
Please show the command you used to start the application.

**Comment by JeromeCisco** [comment]
Try
isAddressUsed.py -h
to have a contextual help

**Comment by beoschma** [comment]
Ok it work, need to indicate the conf file by -c
A default value or prompt could help

**Comment by JeromeCisco** [comment]
Dear Benjamin,
Since this was very important for you I added this in latest version. I hope you will enjoy it.
Thank you!
